apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-django-app
  namespace: default
spec:
  releaseName: my-django-app
  chart:
    spec:
      chart: my-django-app  
      sourceRef:
        kind: GitRepository
        name: my-django-app-repo  # GitRepository 리소스 이름
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jukim4/hello-world-app
      tag: latest
